version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

sphinx:
  fail_on_warning: true
  
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
# system_packages: true
  
formats:
  - pdf
  - epub
